data:
  class_path: open_optformer.training.syne_tune_data.SyneTuneData
  init_args:
    data_path: /syne-tune-benchmarks/data/tokenized_data/concat
    split_names: ['train', 'valid']
devices: auto
eval:
  final_validation: true
  initial_validation: true
  interval: 50
  max_iters: 100000 # loop over entire validation dataset
  max_new_tokens: null
initial_checkpoint_dir: null
logger_name: wandb
model_config:
  attention_logit_softcapping: null
  attention_scores_scalar: null
  attn_bias: false
  bias: false
  block_size: 4096
  final_logit_softcapping: null
  gelu_approximate: none
  hf_config:
    name: Qwen3-80M
    org: Qwen
  latent_attention: null
  lm_head_bias: false
  mlp_class_name: LLaMAMLP
  moe_intermediate_size: null
  n_embd: 512
  head_size: 128
  intermediate_size: 1536
  n_expert: 0
  n_expert_per_token: 0
  n_head: 16
  n_layer: 14
  n_query_groups: 8
  name: Qwen3-80M
  norm_1: true
  norm_2: true
  norm_class_name: RMSNorm
  norm_eps: 1.0e-06
  norm_qk: true
  norm_qk_type: default
  padded_vocab_size: 1185
  padding_multiple: 512
  parallel_residual: false
  post_attention_norm: false
  post_mlp_norm: false
  rope_adjustments: null
  rope_base: 1000000
  rope_condense_ratio: 1
  rope_indices: null
  rope_local_base_freq: null
  rotary_percentage: 1.0
  scale_embeddings: false
  shared_attention_norm: false
  sliding_window_indices: null
  sliding_window_size: null
  vocab_size: 1185
num_nodes: 1
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    betas:
    - 0.9
    - 0.95
    lr: 1e-4
    weight_decay: 0.1
out_dir: /syne-tune-benchmarks/test_qwen3_160M_token_8B_bs_128_all_tokens_lr_1e-4_warump_5p
precision: bf16-mixed
resume: false
seed: 42
tokenizer_dir: /syne-tune-benchmarks/tokenizer
train:
  epochs: null
  global_batch_size: 512
  log_interval: 10
  lr_warmup_steps: 200
  max_norm: 1.0
  max_seq_length: 4096
  max_steps: null
  max_tokens: 8_000_000_000 
  micro_batch_size: 32
  min_lr: 1e-5
  save_interval: 2000
  tie_embeddings: true
log:
  project: "open-optformer"
  run: "qwen3-2M_token_8B_bs_128_all_tokens_lr_1e-4_warumup_5p"
  group: 'concat'
